### ISSUE TITLE
Custom properties - variable was not set on mouseover

### ISSUE THREAD

**Issue by movedoa** [firefox-devtools/devtools-core#1139]
![grafik](https://user-images.githubusercontent.com/13309951/54189267-b8b0b780-44b1-11e9-9c93-96f693a11822.png)

I define some css custom properties at runtime with document.documentElement.style.setProperty.
Everything works but devtools alway say "x was not set".

I am using the latest Firefox DevEdition (66.0b14 (64-Bit))

**Comment by nchevobbe** [comment]
Hello @movedoa , thanks for reporting this issue. This repo is only meant for some specific devtools components, so I created an issue on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1534567 (you should be able to log in with your github account and CC you on the bug)

**Comment by movedoa** [comment]
Thx for the info and the bug entry. Sorry for the noise.
