### ISSUE TITLE
Some in-product Firefox links don't redirect to English (en-US) page if localized version doesn't exis

### ISSUE THREAD

**Issue by atopal** [firefox-devtools/devtools-core#1206]
Hi all,

This is originally from https://github.com/mdn/kuma/issues/7209

**Summary**
Some in-product Firefox links don't redirect to English (en-US) page if localized MDN document version doesn't exist.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Get a localized Firefox Nightly (79.0a1) or Beta (78.0b3). Reproduced this with German (de) and French (fr).
2. Open https://www.mozilla.org
3. Press Shift + F9 to open the web storage inspector.
4. In the left sidebar, click onto a category, e.g. 'Indexed DB'.
5. In the main pane, a text with a link will be shown. Click the link.

**Actual behavior**
https://developer.mozilla.org/Tools/Storage_Inspector/IndexedDB gets opened but MDN claims the page doesn't exist.

**Expected behavior**
English content opened: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector/IndexedDB

**Additional context**
The most likely explanation here is that the links don't have /docs/ in the URL, but we need that on the MDN side to do the proper routing.

**Comment by nchevobbe** [comment]
thanks for the report @atopal !
This repository shouldn't be used anymore, and since this issue relates to the storage inspector, I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1655957 on bugzilla to address it :)

**Comment by atopal** [comment]
Sorry Nic, and thank you!
